FROM node:14

RUN mkdir -p /usr/src/app && chown -R node:node /usr/src/app
RUN mkdir -p /acte && chown -R node:node /acte

USER node
WORKDIR /usr/src/app

COPY --chown=node:node ./app/package*.json ./
COPY --chown=node:node ./app ./
